config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'

  post '/v1/api/product_api', to: 'products#product_create'

  get '/dashboard' => 'home#dashboard', as: :dashboard

  resources :home do
  
  end

  resources :products do
  	get 'cart'
  	get 'checkout'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  #callbacks
  before_save :product_status, :product_gst, :total_price
  
  #Validations
  validates :name, :cost_price, :discount, presence: true

  #Scopes
  scope :by_active, -> { where(status: "active") }

  def product_status
    self.status = "active"
  end

  def product_gst
    if self.product_type == "cloths"
      self.gst_percentage = self.cost_price > 1000 ? 12 : 5
    end
  end

  def total_price
    self.total_price = ((self.cost_price - self.discount)* self.gst_percentage/100) + (self.cost_price - self.discount)
  end

end

app/models/product_type.rb
class ProductType < ApplicationRecord

  #callbacks
  before_save :type_status

  #Validations
  validates :name, presence: true, uniqueness:true

  #Scopes
  scope :by_active, -> { where(status: "active") }

  def type_status
  	self.status = "active"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Callback for authenticate user
	before_action :authenticate_user!

	def after_sign_in_path_for(resource)
		dashboard_path
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	skip_before_action :authenticate_user!, only: [:index]

	def dashboard
		if current_user.user_type == "admin"
			@products = Product.all
			render 'admin_dashboard'
		else
			@products = Product.all
			render 'user_dashboard'
		end
	end

	def index
		@products = Product.all
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
   if @product.save
    redirect_to dashboard_path, flash: {notice: "Product Successfully Created"}
  else
    render :new
  end
end

def edit
  @product = Product.find(params[:id])
end

def update
  @product = Product.find(params[:id])
  if @product.update_attributes(product_params)
    redirect_to dashboard_path, flash: {notice: "Product Successfully Modified"}
  else
    render :edit
  end
end

def cart
  @product = Product.find(params[:product_id])
  @gst = ((@product.cost_price - @product.discount) * @product.gst_percentage/100)
end

def checkout
  @product = Product.find(params[:product_id])
end

private

def product_params
  params.require(:product).permit(:name, :cost_price, :discount, :product_type)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/admin_dashboard.html.erb
  <div class="jumbotron text-center">
    Admin dashboard...!!!
  </div>

  <%= link_to 'Add New Product', new_product_path, class: "btn btn-primary pull-right"  %>

  <div class="container">
    <h2>Products List</h2>  
    <% if @products.present? %>   
    <table class="table table-striped">
      <thead>
        <tr>
         <th>Sl no</th>
         <th>Product name</th>
         <th>Cost price</th>
         <th>Discount</th>
       </tr>
     </thead>
     <% @products.each_with_index do |p, index| %> 
     <tbody>
      <tr>
        <td><%= index+1 %></td>
        <td><%= p.name %></td>
        <td><%= p.cost_price %></td>
        <td><%= p.discount %></td>
        <td><%= link_to 'Modify Product', edit_product_path(p), class: "btn btn-primary"  %></td>
      </tr>
    </tbody>
    <% end %> 
  </table>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="jumbotron text-center">
Welcome to buttercups...!!!
</div>

app/views/home/user_dashboard.html.erb
<div class="jumbotron text-center">
User dashboard...!!!
</div>

<% if @products.present? %>
<% @products.each do |p| %>
<div class="d-block bg-info">
  <h3>Product name :<%= p.name %></h3>
  <p>Price :<%= p.cost_price %></p>
  <p>Discount :<%= p.discount %></p>
  <h3><%= link_to 'Buy Now', product_cart_path(p), class: "btn btn-primary" %></h3>
</div>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Buttercups</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag "application" %>
</head>

<body>

  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>

  <div class="alert alert-success">
    <strong class="notice"><%= notice %></strong>
    <strong class="alert"><%= alert %></strong>
  </div>

  <%= yield %>
</body>
</html>

app/views/products/cart.html.erb
<%= link_to 'Back', dashboard_path, class: "btn btn-primary pull-right" %>

<div class="container">
	<div class="jumbotron">
		<h2>Product Cart :</h2>
		<% if @product.present? %>
		<h3>Product Name : <%= @product.name %></h3>
		<p>Price : <%= @product.cost_price %> INR</p>
		<p>Discount : <%= @product.discount %> INR</p>
		<p>GST : <%= @gst %> INR</p>
		<p>Total Bill Amount : <%= @product.total_price %> INR </p>
		<% end %>
		<%= link_to 'Checkout', product_checkout_path(@product), class: "btn btn-primary checkout_btn" %>
	</div>
</div>

app/views/products/edit.html.erb
<%= link_to 'Back', dashboard_path, class: "btn btn-primary pull-right" %>

<div class="container">
  <h2>Modify product</h2>
  <%= form_for @product, local: true do |form| %>

  <% if @product.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@product.errors.count, "error") %> prohibited
      this product from being saved:
    </h2>
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  
  <div class="form-group">
    <label for="product_name">Product name:</label>
    <%= form.text_field :name, class: "form-control"%>
  </div>

  <div class="form-group">
    <label for="cost_price">Cost price:</label>
    <%= form.text_field :cost_price, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="discount">Discount:</label>
    <%= form.text_field :discount, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="product_type">Product type:</label>
    <%= form.select :product_type, options_for_select(ProductType.by_active.collect{ |p| [p.name] }),{},{ class: "form-control" }%>
  </div>
  
  <%= form.submit 'Save Product', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/products/new.html.erb
<%= link_to 'Back', dashboard_path, class: "btn btn-primary pull-right" %>

<div class="container">
  <h2>Add new product</h2>
  <%= form_for @product, url: products_path, local: true do |form| %>

  <% if @product.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@product.errors.count, "error") %> prohibited
      this product from being saved:
    </h2>
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  
  <div class="form-group">
    <label for="product_name">Product name:</label>
    <%= form.text_field :name, class: "form-control"%>
  </div>

  <div class="form-group">
    <label for="cost_price">Cost price:</label>
    <%= form.text_field :cost_price, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="discount">Discount:</label>
    <%= form.text_field :discount, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="product_type">Product type:</label>
    <%= form.select :product_type, options_for_select(ProductType.by_active.collect{ |p| [p.name] }),{},{ class: "form-control" } %>
  </div>
  
  <%= form.submit 'Create Product', class: "btn btn-primary" %>
  <% end %>
</div>